version: 2
jobs:
  build:
    working_directory: ~/tryme-tutorial
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: 'npm install'
      
  test:
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Run ESLint
          command: 'npm run lint'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master